apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - pvc.yaml
  - secret.yaml
  - service.yaml
  - deployment-redis.yaml
  - deployment-server.yaml
  - deployment-worker.yaml
