apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared-postgres
resources:
  - namespace.yaml
  - cluster.yaml
  - superuser-secret.yaml
  - linkding-database.yaml
  - linkding-db-init-job.yaml
  - commafeed-database.yaml
  - commafeed-db-init-job.yaml
