apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: authentik
data:
  config.yaml: |
    tunnel: homelab
    credentials-file: /etc/cloudflared/creds/credentials.json

    metrics: 0.0.0.0:2000

    no-autoupdate: true

    ingress:
    - hostname: auth.simeonivanov.org
      service: http://authentik.authentik.svc.cluster.local:9000

    - hostname: pgadmin.simeonivanov.org
      service: http://pgadmin.pgadmin.svc.cluster.local:80

    - service: http_status:404
