apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - ../../base/authentik
  - cloudflare-deployment.yaml
  - cloudflare-configmap.yaml
  - cloudflare-secret.yaml
