apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - recurring-jobs/snapshot-daily.yaml
  - ui/auth-secret.yaml
  - ui/middleware.yaml
  - ui/redirect-https.yaml
  - ui/ingressroute-http.yaml
  - ui/ingressroute-https.yaml
