apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - linkding-container-env-secret.yaml
  # - database-secret.yaml  # Temporarily disabled for data export
  # - ingress.yaml
# patchesStrategicMerge:  # Temporarily disabled for data export
#   - deployment-patch.yaml
