---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui-http
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`longhorn2.simeonivanov.org`)
      kind: Rule
      middlewares:
        - name: longhorn-https-redirect
      services:
        - name: longhorn-frontend
          port: 80
