---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui-http
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`longhorn.simeonivanov.org`)
      kind: Rule
      middlewares:
        - name: longhorn-basic-auth
      services:
        - name: longhorn-frontend
          port: 80
