---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui-https
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn2.simeonivanov.org`)
      kind: Rule
      middlewares:
        - name: longhorn-basic-auth
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    certResolver: letsencrypt
