apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base/traefik/
  - dashboard-auth-secret.yaml
  - dashboard-middleware.yaml
  - dashboard-certificate.yaml
  - dashboard-ingressroute.yaml
