apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin
  labels:
    app: pgadmin
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/instance: pgadmin
        app.kubernetes.io/component: web
        policy-type: "app"
    spec:
      securityContext:
        fsGroup: 5050
        runAsUser: 5050
        runAsNonRoot: true
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.11
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          envFrom:
            - configMapRef:
                name: pgadmin-configmap
            - secretRef:
                name: pgadmin-container-env
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
            - name: servers-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgpass
              mountPath: /pgadmin4/pgpass
              subPath: pgpass
              readOnly: true
          resources:
            requests:
              memory: 256Mi
      restartPolicy: Always
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data-pvc
        - name: servers-config
          configMap:
            name: pgadmin-servers
        - name: pgpass
          secret:
            secretName: pgadmin-pgpass
            defaultMode: 0600
