apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - pvc.yaml
  - configmap.yaml
  - servers-config.yaml
  - secrets.yaml
  - service.yaml
  - deployment.yaml
