apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Authentik",
          "Group": "Homelab Databases",
          "Host": "authentik-db-rw.authentik.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "authentik",
          "Username": "authentik",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        },
        "2": {
          "Name": "pgAdmin Config",
          "Group": "Homelab Databases",
          "Host": "pgadmin-db-rw.pgadmin.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "pgadmin",
          "Username": "pgadmin",
          "SSLMode": "prefer",
          "PassFile": "/pgadmin4/pgpass"
        }
      }
    }
