apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:I8JiLqHcTlCtMIWuXboVEMZ2a6KtgU/KntkSHhswDCoL6/T5qfb7TA==,iv:2DGWlLQ3NLj/bvL+7Muz50NVBCA/gfHxxHuRqiycPL4=,tag:0fnOCIjmwQ1k0FzBg2gtuQ==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRDJTZ1NoQWMxMjUyODVT
            NzBXZzBJM2JjcE4vcVNJVWpScWRJR2VpSHhRCm5nWUtSL2hpZkNiWkJ6TllhdHE4
            Ull1ZENDNmhuNkIxOVhGbzQ4MGpRRUkKLS0tIFZDbzBwbVVUblA1NnRwVlF2ZUxX
            a2FSN2QyZExuQ1BWUHIwUDJxbnBDTFkKiWlxFZ0ww5jnMxrYe7YpNnFwtgRpbpNa
            VyNvzKD8hU4mefBOxdOJWjV86lD6OlCdqpAe+KEVA5T0qtEknaRldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T18:22:55Z"
    mac: ENC[AES256_GCM,data:xLytU3QfdKBQPwcNM7BrsM2uWsDJOjCD/D+brTlNaflbNvMHU4pmPPCWaMQGrjGJHv61+XjfZh/zaqeNz62JpC+LpnCmEJfkVnmCD2n+lofD9N3osubcl+ppbqEU/6c9t5PyTDU+8riqsS3NH3Ez3O+1qekpsUuG+bys999FQI4=,iv:qm377zIqK7tkfEwabbjTdECWRj30ljz95ihotJ378Ow=,tag:/hHVnFi5CLPC6bVqDm2qKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
