apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:g2XG1V6105ZHaw1Tw1a+ADzOQaKfR617S0flm9Ypn5NoGbX2L82ccQ==,iv:4RlvpY/+LkEGer37iGE2ktJFbhs4QIXdMCew5kWRlc0=,tag:LV0YmRUngVS9FZSOwYFQMg==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRDJTZ1NoQWMxMjUyODVT
            NzBXZzBJM2JjcE4vcVNJVWpScWRJR2VpSHhRCm5nWUtSL2hpZkNiWkJ6TllhdHE4
            Ull1ZENDNmhuNkIxOVhGbzQ4MGpRRUkKLS0tIFZDbzBwbVVUblA1NnRwVlF2ZUxX
            a2FSN2QyZExuQ1BWUHIwUDJxbnBDTFkKiWlxFZ0ww5jnMxrYe7YpNnFwtgRpbpNa
            VyNvzKD8hU4mefBOxdOJWjV86lD6OlCdqpAe+KEVA5T0qtEknaRldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T18:38:33Z"
    mac: ENC[AES256_GCM,data:3yxWIuHuQlaMVWtbFOFV0qWIU4iZWHr2PuWHhy/eOfb6kbtH/tEdrdR+N0f8Loq7W5nsITZOPMpHmiXAZjZv6NnfToyfs1IzH6sP6IqUx/AQ3IoJq1IGJjo7lfAx0Hm6s81Tj83KxbSP7x/eq9O8oQSrmctiunSsvyTKjlCbL2U=,iv:/E7B2mUJIVwtzYLcS5HWBaLLN+QbfuFkxudq7Q1thsc=,tag:Oc7n8QJW3C60ZHKVQrecyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
