apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: traefik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:g2XG1V6105ZHaw1Tw1a+ADzOQaKfR617S0flm9Ypn5NoGbX2L82ccQ==,iv:4RlvpY/+LkEGer37iGE2ktJFbhs4QIXdMCew5kWRlc0=,tag:LV0YmRUngVS9FZSOwYFQMg==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRDJTZ1NoQWMxMjUyODVT
            NzBXZzBJM2JjcE4vcVNJVWpScWRJR2VpSHhRCm5nWUtSL2hpZkNiWkJ6TllhdHE4
            Ull1ZENDNmhuNkIxOVhGbzQ4MGpRRUkKLS0tIFZDbzBwbVVUblA1NnRwVlF2ZUxX
            a2FSN2QyZExuQ1BWUHIwUDJxbnBDTFkKiWlxFZ0ww5jnMxrYe7YpNnFwtgRpbpNa
            VyNvzKD8hU4mefBOxdOJWjV86lD6OlCdqpAe+KEVA5T0qtEknaRldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T19:25:38Z"
    mac: ENC[AES256_GCM,data:tKnG/qWe0cpOLAJ7bKyzbF9Hm3gsm/l6kqQvyinoZvZP5BnIggA+BN9sfq+TEHJRj737LDYOFK3vwaQ/odPw93iIhqGDCgOePEqpc9oukPX9WccpnTrI/6M6gyunj34xbQRA+AgfvyP611SnN7UCWVtlb9LYd1sVNJDT7BraOiY=,iv:B+0czdxPWnGyDHglai00+9OBdmNJYgekB/kgT6F+RIU=,tag:AhFfMwPDWmnYjZJrRTgRZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
