apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:BukUhI//,iv:cLkfPUR5rDiY70FRrapKLB3v5OIAyG+me9hUfyvc6HI=,tag:imeuT5mOz1yRN9ZrVsjZog==,type:str]
  admin-password: ENC[AES256_GCM,data:rkZdJX73pzw=,iv:c7v7Zid5ca2zFLLjlVs9DH5C5nePC7u6DAhkxbWRvLo=,tag:QJqH92Uzjpeu8rB3SeFaYA==,type:str]
sops:
  age:
    - recipient: age1ppc8crvqj46l02zshwrmngfq6ykr9y9zlt7sty4nwamr08r3yefswufxlm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOG56Y3NQeFhSU09pdnlF
        eCtzTG4zZDRsL3dBbU94VTE3RnVUaFFMdFhzClJiaFBjK2tJelp6aXQ5UnpuRlFN
        cW5zUURsdkwxdDBUbFFRNVd4ZU5zSmsKLS0tIEVZZFlqekxiZ0o0ajdLNUFMVXZX
        RVU1UzBWODBsSUhienNQOU9NekZHaUUKpYF6rJMfpqNhWK5meKaEGb/vM1XTVhOZ
        lXRQb5dT6FI5R0E740Rk0rKYeeUd0e8vEZcHC+kVBSIBqEd39YiqwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T21:03:47Z"
  mac: ENC[AES256_GCM,data:LivDjZRoXh26pr1V0U/9jAXnab8VGkMf9doy/680ZUBpP7+j7QL5z+r7yg94Yo7c0OIrcQv+wi1Bwu2fB8CCBukmil3grtL/kJUO+45b/+TUS5ic7KZYKLYqjwWh2xqtErJimS+wgra0QF99lcC3Vdj8Xs8lVbnI0ZwrRBzijIY=,iv:epIOSKNfCtoLjO8cUH91Rr3++Gda6ny1fwH+x+nFjhI=,tag:gnUsudan+KlKArVcP3jE0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
