apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:YvdPVBY=,iv:+pRqyCLWfM4/6ECvDbMDNE9ppPvpnLwZgL3jnsMTjH8=,tag:ymCcnfpCVuaagNIsKaCMfg==,type:str]
    admin-password: ENC[AES256_GCM,data:5p/UXuTdqzR1DIk3JRTw3iHVPZjJn6rH46pTGSv/tHE=,iv:+h17Is+JKGg16+p3DOkrwclCYp13822zwpF8fZHJgmY=,tag:/jVvZsUKxaYekYWGiDLK1Q==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ0pYbDZPUkM3aXQxVnJ1
            WTlJVWZLOGgrbHNqQXl6ZHpnUXFaUXpHc1FvCnZIN1kzMitkQUJHaDFndk1Xb0Jo
            aHlWUU5WaG9qb1B1TmkwdFF3Vm5rZXMKLS0tIHo4OERyaUNBQkJESDNoc1FCTmJ2
            ZCtUNVRsaUU2UUowbnJ5N05ReUZoaG8KFkfIpWCAqQdgvQ8vw50GeMdlo73Q735S
            rjnXcY/jlYr/j6OUwin2aR2qz8aUq84+hIeJqBvXSQWvgYItLzIU+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T20:59:43Z"
    mac: ENC[AES256_GCM,data:Pwz5fznQRq1C9UQxM0nI7poCuGtkiQ1QdmBjh9uY2Y7fGaGrRglaPByHiYZjbcRBJvtgUk5Of2ItfyLEQa4tEsqjiPWBI1qOoEsyWs9hZVelvp/YaktgABilnCkCEIMcOV9dEDrw+DdgEAmtk9KZA3zIxmyU6A/WevzAOPPz8yw=,iv:Jf2jl32XYhR8kCcccTMBr/hr4bszaUTJC732VE3XVR4=,tag:w6iNs7n2bxqjjG1TBxCeWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
