apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-admin-secret.yaml
  - grafana-tls-secret.yaml
  - grafana-ingressroute-https.yaml
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/k8s-views-global.json
      - dashboards/k8s-views-nodes.json
      - dashboards/k8s-views-pods.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kubernetes
