apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
  namespace: renovate
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "Simeon's Renovate Bot <bot@renovateapp.com>"
  RENOVATE_PLATFORM: "github"
