apiVersion: v1
kind: Service
metadata:
  name: commafeed
  labels:
    app: commafeed
    app.kubernetes.io/name: commafeed
    app.kubernetes.io/instance: commafeed
    app.kubernetes.io/component: web
spec:
  selector:
    app: commafeed
  type: ClusterIP
  ports:
    - port: 8082
